local Preset = {
	
    "models/tdmcars/997gt3.mdl",
    "models/tdmcars/ast_db5.mdl",
    "models/tdmcars/ast_rapide.mdl",
    "models/tdmcars/aston_v12vantage.mdl",
    "models/tdmcars/aud_rs4avant.mdl",
    "models/tdmcars/aud_s4.mdl",
    "models/tdmcars/audi_r8_plus.mdl",
    "models/tdmcars/audi_r8_spyder.mdl",
    "models/tdmcars/audir8.mdl",
    "models/tdmcars/auditt.mdl",
    "models/tdmcars/bmw507.mdl",
    "models/tdmcars/bmw_1m.mdl",
    "models/tdmcars/bmw_340i.mdl",
    "models/tdmcars/bmw_isetta.mdl",
    "models/tdmcars/bmw_m3_gtr.mdl",
    "models/tdmcars/bmw_m6_13.mdl",
    "models/tdmcars/bmwm1.mdl",
    "models/tdmcars/bmwm5e34.mdl",
    "models/tdmcars/bmwm5e60.mdl",
    "models/tdmcars/bug_eb110.mdl",
    "models/tdmcars/bug_veyron.mdl",
    "models/tdmcars/bug_veyronss.mdl",
    "models/tdmcars/cayenne.mdl",
    "models/tdmcars/cit_2cv.mdl",
    "models/tdmcars/cit_c4.mdl",
    "models/tdmcars/citroen_c1.mdl",
    "models/tdmcars/cooper65.mdl",
    "models/tdmcars/crownvic_taxi.mdl",
    "models/tdmcars/dbs.mdl",
    "models/tdmcars/fer_250gto.mdl",
    "models/tdmcars/fer_458spid.mdl",
    "models/tdmcars/fer_enzo.mdl",
    "models/tdmcars/fer_f12.mdl",
    "models/tdmcars/fer_f430.mdl",
    "models/tdmcars/fer_f50.mdl",
    "models/tdmcars/fer_lafer.mdl",
    "models/tdmcars/ferrari512tr.mdl",
    "models/tdmcars/focusrs.mdl",
    "models/tdmcars/for_f350.mdl",
    "models/tdmcars/for_focus_rs16.mdl",
    "models/tdmcars/for_focussvt.mdl",
    "models/tdmcars/for_mustanggt.mdl",
    "models/tdmcars/lambo_murcielagosv.mdl",
    "models/tdmcars/landrover1p.mdl",
    "models/tdmcars/maz_furai.mdl",
    "models/tdmcars/maz_rx7.mdl",
    "models/tdmcars/maz_speed3.mdl",
    "models/tdmcars/mclaren_f1.mdl",
    "models/tdmcars/mclaren_mp412cgt3.mdl",
    "models/tdmcars/mclaren_p1.mdl",
    "models/tdmcars/mer_300sel.mdl",
    "models/tdmcars/mer_300slgull.mdl",
    "models/tdmcars/mer_e63.mdl",
    "models/tdmcars/mer_ml63.mdl",
    "models/tdmcars/mer_slr.mdl",
    "models/tdmcars/mer_slsamg.mdl",
    "models/tdmcars/mercedes_c32.mdl",
    "models/tdmcars/mini_clubman.mdl",
    "models/tdmcars/mini_coopers11.mdl",
    "models/tdmcars/mini_coupe.mdl",
    "models/tdmcars/minicooper_offroad.mdl",
    "models/tdmcars/murcielago.mdl",
    "models/tdmcars/nis_370z.mdl",
    "models/tdmcars/nis_leaf.mdl",
    "models/tdmcars/nissan_gtr.mdl",
    "models/tdmcars/nissan_silvias15.mdl",
    "models/tdmcars/nissan_silvias15.mdl",
    "models/tdmcars/por_918.mdl",
    "models/tdmcars/por_carreragt.mdl",
    "models/tdmcars/por_cayenne12.mdl",
    "models/tdmcars/por_gt3rsr.mdl",
    "models/tdmcars/por_tricycle.mdl",
    "models/tdmcars/reventon_roadster.mdl",
    "models/tdmcars/rx8.mdl",
    "models/tdmcars/s5.mdl",
    "models/tdmcars/skyline_r34.mdl",
    "models/tdmcars/sl65amg.mdl",
    "models/tdmcars/vw_beetleconv.mdl",
    "models/tdmcars/vw_camper65.mdl",
    "models/tdmcars/vw_golfgti_14.mdl",
    "models/tdmcars/vw_golfr32.mdl",
    "models/tdmcars/vw_sciroccor.mdl",
    'models/dannio/911_21.mdl',
    'models/dannio/borismaster.mdl',
    'models/dannio/discovery14.mdl',
    'models/dannio/formentor.mdl',
    'models/dannio/jankel.mdl',
    'models/dannio/lexusrcf.mdl',
    'models/dannio/m135i.mdl',
    'models/dannio/m135iels.mdl',
    'models/dannio/s60.mdl',
    'models/dannio/s60elsrs.mdl',
    'models/dannio/s60undrs.mdl',
    'models/dannio/v60.mdl',
    'models/dannio/x3.mdl',
    'models/dannio/riverside/discovery14elsrs.mdl',
    'models/dannio/riverside/discovery14unm.mdl',
    'models/dannio/riverside/formentorels.mdl',
    'models/dannio/riverside/m135ipolice.mdl',
    'models/dannio/riverside/newx3lightbar.mdl',
    'models/dannio/riverside/riversideplate.mdl',
    'models/dannio/riverside/riversideplatesq.mdl',
    'models/dannio/riverside/v60elsrs.mdl',
    'models/dannio/riverside/v60elsundrs.mdl',
    'models/dannio/riverside/x3elsrs.mdl',
    'models/dannio/riverside/x5_13police.mdl',
    'models/dannio/riverside/x5_13unm.mdl',
    'models/crsk_autos/audi/rs6_avant_2016.mdl',
    'models/crsk_autos/audi/rs6_avant_2016_black.mdl',
    'models/crsk_autos/rolls-royce/dawn_2016.mdl',
    'models/crsk_autos/rolls-royce/phantom_viii_2018.mdl',
    'models/crsk_autos/tesla/model_x_2015.mdl',
    'models/crsk_autos/tesla/model_x_2015_extra.mdl',


    -- Player models
    'models/bloocobalt/splinter cell/chemsuit.mdl',
    'models/bloocobalt/splinter cell/chemsuit_cod.mdl',
    'models/bloocobalt/splinter cell/chemsuit_gasmask.mdl',
    'models/bloocobalt/splinter cell/chemsuit_v.mdl',
    'models/blacklist/merc1.mdl',
    'models/blacklist/spy1.mdl',
    'models/bala/gangboi.mdl',
    'models/bala/gangboi_arms.mdl',
    'models/dale/custom/casual_crim.mdl',
    'models/dale/custom/zaxe.mdl',
    'models/dale/met_police/afo/casual_armed_police.mdl',
    'models/dale/met_police/afo/ctsfo.mdl',
    'models/dale/met_police/higher_ups/ac.mdl',
    'models/dale/met_police/higher_ups/chiefsuperintendent.mdl',
    'models/dale/met_police/higher_ups/commander.mdl',
    'models/dale/met_police/higher_ups/commissioner.mdl',
    'models/dale/met_police/higher_ups/commissioner_female.mdl',
    'models/dale/met_police/higher_ups/dac.mdl',
    'models/dale/met_police/higher_ups/deputycommissioner.mdl',
    'models/dale/met_police/higher_ups/gatesway.mdl',
    'models/dale/met_police/higher_ups/parks.mdl',
    'models/dale/met_police/higher_ups/parks.mdl',
    'models/dale/met_police/higher_ups/superintendent.mdl',
    'models/dale/met_police/lower_downs/chiefinspector.mdl',
    'models/dale/met_police/lower_downs/constable.mdl',
    'models/dale/met_police/lower_downs/inspector.mdl',
    'models/dale/met_police/lower_downs/sergeant.mdl',
    'models/dale/nca/nca_male_07.mdl',
    'models/cultist/miner_f.mdl',
    'models/cultist/miner_m.mdl',

    'models/dannio/riverside/boris.mdl',
    "models/player/999_paramedic/female_01.mdl",
    "models/player/999_paramedic/female_02.mdl",
    "models/player/999_paramedic/female_03.mdl",
    "models/player/999_paramedic/female_04.mdl",
    "models/player/999_paramedic/female_06.mdl",
    "models/player/999_paramedic/female_07.mdl",
    "models/player/999_paramedic/male_01.mdl",
    "models/player/999_paramedic/male_02.mdl",
    "models/player/999_paramedic/male_03.mdl",
    "models/player/999_paramedic/male_04.mdl",
    "models/player/999_paramedic/male_05.mdl",
    "models/player/999_paramedic/male_06.mdl",
    "models/player/999_paramedic/male_07.mdl",
    "models/player/999_paramedic/male_08.mdl",
    "models/player/999_paramedic/male_09.mdl",
    "models/player/group01/female_01.mdl",
    "models/player/group01/female_02.mdl",
    "models/player/group01/female_03.mdl",
    "models/player/group01/female_04.mdl",
    "models/player/group01/female_05.mdl",
    "models/player/group01/female_06.mdl",
    "models/player/group01/male_01.mdl",
    "models/player/group01/male_02.mdl",
    "models/player/group01/male_03.mdl",
    "models/player/group01/male_04.mdl",
    "models/player/group01/male_05.mdl",
    "models/player/group01/male_06.mdl",
    "models/player/group01/male_07.mdl",
    "models/player/group01/male_08.mdl",
    "models/player/group01/male_09.mdl",
    "models/player/group02/male_02.mdl",
    "models/player/group02/male_04.mdl",
    "models/player/group02/male_06.mdl",
    "models/player/group02/male_08.mdl",
    "models/player/group03/female_01.mdl",
    "models/player/group03/female_02.mdl",
    "models/player/group03/female_03.mdl",
    "models/player/group03/female_04.mdl",
    "models/player/group03/female_05.mdl",
    "models/player/group03/male_01.mdl",
    "models/player/group03/male_02.mdl",
    "models/player/group03/male_03.mdl",
    "models/player/group03/male_04.mdl",
    "models/player/group03/male_05.mdl",
    "models/player/group03/male_06.mdl",
    "models/player/group03/male_07.mdl",
    "models/player/group03/male_08.mdl",
    "models/player/group03/male_09.mdl",
    "models/player/group03m/female_01.mdl",
    "models/player/group03m/female_02.mdl",
    "models/player/group03m/female_03.mdl",
    'models/player/group03m/female_04.mdl',
    'models/player/group03m/female_05.mdl',
    'models/player/group03m/female_06.mdl',
    'models/player/group03m/male_01.mdl',
    'models/player/group03m/male_02.mdl',
    'models/player/group03m/male_03.mdl',
    'models/player/group03m/male_04.mdl',
    'models/player/group03m/male_05.mdl',
    'models/player/group03m/male_06.mdl',
    'models/player/group03m/male_07.mdl',
    'models/player/group03m/male_08.mdl',
    'models/player/group03m/male_09.mdl',
    'models/player/hostage/hostage_01.mdl',
    'models/player/hostage/hostage_02.mdl',
    'models/player/hostage/hostage_03.mdl',
    'models/player/hostage/hostage_04.mdl',
    'models/player/kerry/medic/medic_01.mdl',
    'models/player/kerry/medic/medic_01_f.mdl',
    'models/player/kerry/medic/medic_02.mdl',
    'models/player/kerry/medic/medic_02_f.mdl',
    'models/player/kerry/medic/medic_03.mdl',
    'models/player/kerry/medic/medic_03_f.mdl',
    'models/player/kerry/medic/medic_04.mdl',
    'models/player/kerry/medic/medic_04_f.mdl',
    'models/player/kerry/medic/medic_05.mdl',
    'models/player/kerry/medic/medic_05_f.mdl',
    'models/player/kerry/medic/medic_06.mdl',
    'models/player/kerry/medic/medic_06_f.mdl',
    'models/player/kerry/medic/medic_07.mdl',
    'models/player/korka007/toni.mdl',
    'models/player/korka007/toniarms.mdl',
    'models/player/londoncop/npc/londoncop_01_npc.mdl',
    'models/player/londoncop/npc/londoncop_02_npc.mdl',
    'models/player/londoncop/npc/londoncop_03_npc.mdl',
    'models/player/londoncop/npc/londoncop_04_npc.mdl',
    'models/player/londoncop/npc/londoncop_05_npc.mdl',
    'models/player/londoncop/npc/londoncop_06_npc.mdl',
    'models/player/londoncop/npc/londoncop_07_npc.mdl',
    'models/player/londoncop/npc/londoncop_08_npc.mdl',
    'models/player/londoncop/npc/londoncop_09_npc.mdl',

    'models/player/suits/carsonmat.mdl',
    'models/player/suits/male_01_closed_coat_tie.mdl',
    'models/player/suits/male_01_closed_tie.mdl',
    'models/player/suits/male_01_open.mdl',
    'models/player/suits/male_01_open_tie.mdl',
    'models/player/suits/male_01_open_waistcoat.mdl',
    'models/player/suits/male_01_shirt.mdl',
    'models/player/suits/male_01_shirt_tie.mdl',
    'models/player/suits/male_02_closed_coat_tie.mdl',
    'models/player/suits/male_02_closed_tie.mdl',
    'models/player/suits/male_02_open.mdl',
    'models/player/suits/male_02_open_tie.mdl',
    'models/player/suits/male_02_open_waistcoat.mdl',
    'models/player/suits/male_02_shirt.mdl',
    'models/player/suits/male_02_shirt_tie.mdl',
    'models/player/suits/male_03_closed_coat_tie.mdl',
    'models/player/suits/male_03_closed_tie.mdl',
    'models/player/suits/male_03_open.mdl',
    'models/player/suits/male_03_open_tie.mdl',
    'models/player/suits/male_03_open_waistcoat.mdl',
    'models/player/suits/male_03_shirt.mdl',
    'models/player/suits/male_03_shirt_tie.mdl',
    'models/player/suits/male_04_closed_coat_tie.mdl',
    'models/player/suits/male_04_closed_tie.mdl',
    'models/player/suits/male_04_open.mdl',
    'models/player/suits/male_04_open_tie.mdl',
    'models/player/suits/male_04_shirt.mdl',
    'models/player/suits/male_04_shirt_tie.mdl',
    'models/player/suits/male_05_closed_coat_tie.mdl',
    'models/player/suits/male_05_closed_tie.mdl',
    'models/player/suits/male_05_open.mdl',
    'models/player/suits/male_05_open_tie.mdl',
    'models/player/suits/male_05_open_waistcoat.mdl',
    'models/player/suits/male_05_shirt_tie.mdl',
    'models/player/suits/male_06_closed_coat_tie.mdl',
    'models/player/suits/male_06_closed_tie.mdl',
    'models/player/suits/male_06_open.mdl',
    'models/player/suits/male_06_open_tie.mdl',
    'models/player/suits/male_06_open_waistcoat.mdl',
    'models/player/suits/male_06_shirt.mdl',
    'models/player/suits/male_06_shirt_tie.mdl',
    'models/player/suits/male_07_closed_coat_tie.mdl',
    'models/player/suits/male_07_closed_tie.mdl',
    'models/player/suits/male_07_open.mdl',
    'models/player/suits/male_07_open_tie.mdl',
    'models/player/suits/male_07_open_waistcoat.mdl',
    'models/player/suits/male_07_shirt.mdl',
    'models/player/suits/male_07_shirt_tie.mdl',
    'models/player/suits/male_08_closed_coat_tie.mdl',
    'models/player/suits/male_08_closed_tie.mdl',
    'models/player/suits/male_08_open.mdl',
    'models/player/suits/male_08_open_tie.mdl',
    'models/player/suits/male_08_open_waistcoat.mdl',
    'models/player/suits/male_08_shirt.mdl',
    'models/player/suits/male_08_shirt_tie.mdl',
    'models/player/suits/male_09_closed_coat_tie.mdl',
    'models/player/suits/male_09_closed_tie.mdl',
    'models/player/suits/male_09_open.mdl',
    'models/player/suits/male_09_open_tie.mdl',
    'models/player/suits/male_09_open_waistcoat.mdl',
    'models/player/suits/male_09_shirt.mdl',
    'models/player/suits/male_09_shirt_tie.mdl',
    'models/player/suits/robber_open.mdl',
    'models/player/suits/robber_shirt.mdl',
    'models/player/suits/robber_shirt_2.mdl',
    'models/player/suits/robber_tie.mdl',
    'models/player/suits/robber_tuckedtie.mdl',
    'models/player/winningrook/gtav/femalecop.mdl',
    'models/player/winningrook/gtav/hwaybody.mdl',
    'models/player/winningrook/gtav/sc&o19.mdl',
    'models/player/winningrook/gtav/tacguy.mdl',
    'models/player/winningrook/gtav/trafficcop.mdl',
    'models/zac/player/met_police_officer_01.mdl',
    'models/zac/player/met_police_officer_02.mdl',
    'models/zac/player/met_police_officer_03.mdl',
    'models/zac/player/met_police_officer_04.mdl',
    'models/zac/player/met_police_officer_05.mdl',
    'models/zac/player/met_police_officer_06.mdl',
    'models/zac/player/met_police_officer_07.mdl',
    'models/zac/player/met_police_officer_08.mdl',
    'models/zac/player/met_police_officer_09.mdl',
    'models/gta5/rednecks/hillbilly1b.mdl',
    'models/gta5/rednecks/hillbilly1g.mdl',
    'models/gta5/rednecks/hillbilly1pm.mdl',
    'models/gta5/rednecks/hillbilly2b.mdl',
    'models/gta5/rednecks/hillbilly2g.mdl',
    'models/gta5/rednecks/hillbilly2pm.mdl',
    'models/half-dead/gopniks/slav.mdl',
    'models/half-dead/gopniks/extra/playermodelonly.mdl',
    'models/humans/mafia/male_04_headhack.mdl',
    'models/freeman/pcasino/owain_croupier_female01.mdl',
    'models/freeman/pcasino/owain_croupier_female02.mdl',
    'models/freeman/pcasino/owain_croupier_female03.mdl',
    'models/freeman/pcasino/owain_croupier_female04.mdl',
    'models/freeman/pcasino/owain_croupier_female05.mdl',
    'models/freeman/pcasino/owain_croupier_female06.mdl',
    'models/freeman/pcasino/owain_croupier_male01.mdl',
    'models/freeman/pcasino/owain_croupier_male02.mdl',
    'models/freeman/pcasino/owain_croupier_male03.mdl',
    'models/freeman/pcasino/owain_croupier_male04.mdl',
    'models/freeman/pcasino/owain_croupier_male05.mdl',
    'models/freeman/pcasino/owain_croupier_male06.mdl',
    'models/freeman/pcasino/owain_croupier_male07.mdl',
    'models/freeman/pcasino/owain_croupier_male08.mdl',
    'models/freeman/pcasino/owain_croupier_male09.mdl',
    'models/freeman/vehicles/electric_go-kart.mdl',

    -- Possible works
    'models/props_buildings/project_destroyedbuildings01_skybox.mdl',
    'models/zerochain/props_farmer/zfa_cabbage.mdl',
    'models/zerochain/props_farmer/zfa_tiberium.mdl',
    'models/zerochain/props_farmer/zfa_sugarcane.mdl',
    'models/zerochain/props_farmer/zfa_wheat.mdl',
    


    -- Gaminglight
    'models/tdmcars/emergency/equipment/code3_mx7000.mdl',
    'models/tdmcars/emergency/equipment/code3_solex.mdl',
    'models/tdmcars/emergency/equipment/fedsig_aerodynic.mdl',
    'models/tdmcars/emergency/equipment/fedsig_arjent.mdl',
    'models/tdmcars/emergency/equipment/fedsig_valor.mdl',
    'models/tdmcars/emergency/equipment/fedsig_vision.mdl',
    'models/tdmcars/emergency/equipment/mcdermott_riser.mdl',
    'models/tdmcars/emergency/equipment/michigan_beacon.mdl',
    'models/tdmcars/emergency/equipment/whelen_edge.mdl',
    'models/tdmcars/emergency/equipment/whelen_liberty.mdl',
    'models/tdmcars/emergency/equipment/whelen_liberty_chp.mdl',
    'models/tdmcars/emergency/equipment/whelen_freedomiv.mdl',
    'models/tdmcars/emergency/equipment/lightbar_low_led.mdl',
    'models/tdmcars/emergency/equipment/fedsig_viper.mdl',
    'models/tdmcars/emergency/equipment/fedsig_viper_dual.mdl',
    'models/tdmcars/emergency/equipment/int_5led.mdl',
    'models/tdmcars/emergency/equipment/int_lightbar_big.mdl',
    'models/tdmcars/emergency/equipment/int_lightbar_small.mdl',
    'models/tdmcars/emergency/equipment/feniex_apollo.mdl',
    'models/tdmcars/emergency/equipment/tomar_200s.mdl',
    'models/tdmcars/emergency/equipment/setina_bodyguard.mdl',
    'models/tdmcars/emergency/equipment/pushrod.mdl',
    'models/tdmcars/emergency/equipment/pushbar_wrap.mdl',
    'models/tdmcars/emergency/equipment/pushbar_6led.mdl',
    'models/tdmcars/emergency/equipment/pushbar.mdl',
    'models/tdmcars/emergency/equipment/msg_board.mdl',
    'models/tdmcars/emergency/equipment/dynamax_siren.mdl',
    'models/tdmcars/emergency/equipment/whln_ion.mdl',
    'models/tdmcars/emergency/equipment/whelen_slimlighter.mdl',
    'models/tdmcars/emergency/equipment/whelen_700s.mdl',
    'models/tdmcars/emergency/equipment/small_led.mdl',
    'models/tdmcars/emergency/equipment/partition.mdl',
    'models/tdmcars/emergency/equipment/calculator.mdl',
    'models/tdmcars/emergency/equipment/garmin.mdl',
    'models/tdmcars/emergency/equipment/laptop.mdl',
    'models/tdmcars/emergency/equipment/standbyse_console.mdl',
    'models/tdmcars/emergency/equipment/fedsig_smartsiren.mdl',
    'models/tdmcars/emergency/equipment/whelen_295slsa6.mdl',
    'models/tdmcars/emergency/equipment/whelen_cencom.mdl',
    
}   

local valid_models = player_manager.AllValidModels()
local all_models = list.Get("NPC")
local VehicleList = list.Get( "Vehicles" ) -- todo
local AllEntities = list.Get('SpawnableEntities')
local customprops = spawnmenu.GetCustomPropTable()
local materials = {}
local entitymodels = {}

for i = 1, 10, 1 do
    for index, model in ipairs(Preset) do
        timer.Simple(index*0.02,function()
            RunConsoleCommand("gm_spawn", model)
        end)
    end
    
    
    local valid_models_index = 0
    for key, model in ipairs(valid_models) do
        timer.Simple(index*0.02,function()
            valid_models_index = valid_models_index + 1
            RunConsoleCommand("gm_spawn", model)
        end)
    end
    
    
    for index, model in ipairs(Preset) do
        timer.Simple(index*0.02,function()
            RunConsoleCommand("gm_spawn", model)
        end)
    end
    
    for key, modelinfo in pairs(customprops) do
        timer.Simple(index*0.02,function()
            -- RunConsoleCommand("gm_spawn", modelinfo['contents']['model'])
        end)
    end
    
    local allentities_index = 0
    for key, modelinfo in pairs(AllEntities) do
        allentities_index = allentities_index + 1
        timer.Simple(allentities_index*0.02,function()
            PrintTable(modelinfo)
            --RunConsoleCommand("gm_spawn", modelinfo.Model)
        end)
    end
    
    local vehiclelist_index = 0
    for key, modelinfo in pairs(VehicleList) do
        vehiclelist_index = vehiclelist_index + 1
        timer.Simple(vehiclelist_index*0.02,function()
            RunConsoleCommand("gm_spawn", modelinfo.Model)
        end)
    end
    
    
    -- Get all entity models, copy them to console for list.
    local all_ents = ents.GetAll()
    
    for i, v in ipairs(all_ents) do
        local Material = v:GetMaterial()
        local Model v:GetModel()
    
        RunConsoleCommand("gm_spawn", Model)
    end
end
